### ISSUE TITLE
集成常用的正则校验库来增强易用性

### ISSUE THREAD

**Issue by Allen-1998** [LittleSound/slimeform#28]
#### 这是一个新的想法，下面用是什么，为什么，怎么做的方式来表达一下我的观点：

1. 是什么？
   - 集成常用的正则校验库，使用户在需要一些常用的表单校验规则时直接 import 调用即可。

2. 为什么？
   - 作为一个表单校验库，形影不离的就是表单校验规则
   - 对于正则水平不佳的用户而言会是很有帮助的（无需自己查找、试错，ps：就我接触到的很多甚至几年的前端正则依然一塌糊涂）
   - 就像 `vite` 会集成 `rollup`的生态插件，`unocss` 会集成 `tailwind css`、`windi css`的匹配规则
   - 其他的表单库貌似没有实现这一点的（也许是还没想到，也许是因为没必要。。。）

3. 怎么做？
   - 或许参考一下 antfu 对 icon 的集成方式？（收录常用的并支持自动引入、按需打包）

我个人觉得这个功能对于一部分的用户群体来说是很有帮助的，但是如果确定要做的话具体的实现方式还有待商讨，目前我了解到的一个比较不错的常用正则库是[any-rule](https://github.com/any86/any-rule)。

**Comment by Allen-1998** [comment]
发现 todo list 里貌似有相关内容 XD

**Comment by LittleSound** [comment]
这个周末我会做接入 yup 的工作

**Comment by LittleSound** [comment]
我已经添加了讲述如何使用 Yup 作为规则的文档：[使用 Yup 作为规则](https://github.com/LittleSound/slimeform/blob/HEAD/README.zh-Hans.md#%E4%BD%BF%E7%94%A8-yup-%E4%BD%9C%E4%B8%BA%E8%A7%84%E5%88%99)
