### ISSUE TITLE
rule 中的函数应当可以返回 undefined 表示没有错误

### ISSUE THREAD

**Issue by Misaka-0x447f** [LittleSound/slimeform#29]
图中这句 return false 比较没必要。
![image](https://user-images.githubusercontent.com/15797507/171783531-1a9e5255-5f12-4699-b890-c54440d3c2f8.png)

**Comment by LittleSound** [comment]
> 图中这句 return false 比较没必要。 ![image](https://user-images.githubusercontent.com/15797507/171783531-1a9e5255-5f12-4699-b890-c54440d3c2f8.png)

false 和 string 都标识验证失败。
正确的用法是
```ts
() => <boolean 表达式> || '<message>'
```

截图当中的代码不完整，表述也不是很清晰，这个问题我先关闭了。
