### ISSUE TITLE
Feature Request: disable auto update `status`？

### ISSUE THREAD

**Issue by xuzuodong** [LittleSound/slimeform#44]
Hello, Dalao!

When using slimeform, is it possible to pass in an options like this: 

``` ts
const { form, status, verify } = useForm({
    form: () => ({
        userName: '',
        ...
    }),

    lazy: true,
})
```

When `lazy` is set to true, data updates in `form` won't automatically cause `status` to change, unless user call `verify()` or `status.userName.verify()` manually. 

I think it can be useful if I want to verify content in a Text Input **after it's done inputing, i.e. blurred**. 

Similar behavior can be found here: https://quasar.dev/vue-components/input#example--lazy-rules .

**Comment by LittleSound** [comment]
Looks good, maybe you can implement this feature.

I have another neng solution here that achieves a similar effect.
You can change the v-model to v-model.lazy 

Reference document: https://vuejs.org/api/built-in-directives.html#v-model
