### ISSUE TITLE
对于 src/index.ts 的更改建议

### ISSUE THREAD

**Issue by Misaka-0x447f** [LittleSound/slimeform#8]
对于不关心返回值的情况，请使用 `unknown` 类型。
https://github.com/LittleSound/slimeform/blob/93eaef52bddd45d3435c8ef41710d31586770e7f/src/index.ts#L44
建议改用 jsdoc 格式。
https://github.com/LittleSound/slimeform/blob/93eaef52bddd45d3435c8ef41710d31586770e7f/src/index.ts#L40-L43
如果不使用 this，改用箭头函数更安全一些。
https://github.com/LittleSound/slimeform/blob/93eaef52bddd45d3435c8ef41710d31586770e7f/src/index.ts#L76
https://github.com/LittleSound/slimeform/blob/93eaef52bddd45d3435c8ef41710d31586770e7f/src/index.ts#L53
if 可优化以减少嵌套。
https://github.com/LittleSound/slimeform/blob/93eaef52bddd45d3435c8ef41710d31586770e7f/src/index.ts#L92-L103
变量名意味不明；为什么使用 any？
https://github.com/LittleSound/slimeform/blob/93eaef52bddd45d3435c8ef41710d31586770e7f/src/index.ts#L159-L161
建议使用语义化工具 `import('lodash').isFunction`。
https://github.com/LittleSound/slimeform/blob/93eaef52bddd45d3435c8ef41710d31586770e7f/src/index.ts#L164

**Comment by LittleSound** [comment]
感谢你的建议。我有空的时候会去优化代码结构。
